### ISSUE TITLE
Meet Our Developers Text Overlapping

### ISSUE THREAD

**Issue by fishcharlie** [gregbrunk/politicator#12]
In the image below the "Meet Our Developers" text is overlapping the main text in that section. It makes it harder to read and understand. Would be good to figure out a way to fix this and make it more clean. 

<img width="1265" alt="screen shot 2016-08-15 at 4 17 41 pm" src="https://cloud.githubusercontent.com/assets/860375/17681581/d28d2950-6303-11e6-93c6-9135240e3dd8.png">

**Comment by gregbrunk** [comment]
This doesn't happen until pretty small vertical screen sizes ( < 790px ), which isn't really practical for us to account for right now. The site is mobile optimized though for small screens (see screenshots). I did bump up the top margin a bit to give a little more vertical room, though! 

<img width="468" alt="screen shot 2016-08-15 at 5 22 18 pm" src="https://cloud.githubusercontent.com/assets/19507409/17683050/2eb17fac-630d-11e6-84f5-dacf8f59561b.png">
<img width="1596" alt="screen shot 2016-08-15 at 5 23 13 pm" src="https://cloud.githubusercontent.com/assets/19507409/17683051/2ec23f40-630d-11e6-8ce5-eec7b5bfe972.png">
