### ISSUE TITLE
Make summary text more readable

### ISSUE THREAD

**Issue by fishcharlie** [gregbrunk/politicator#13]
The text in the image below overlaps and the colors get messed up and is very hard to read. Would be awesome to contain text in that background image and make it more readable. 

<img width="1258" alt="screen shot 2016-08-15 at 4 19 29 pm" src="https://cloud.githubusercontent.com/assets/860375/17681623/12e4e448-6304-11e6-8186-8efa61aff29e.png">

**Comment by gregbrunk** [comment]
Fixed! 
<img width="1745" alt="screen shot 2016-08-15 at 5 31 27 pm" src="https://cloud.githubusercontent.com/assets/19507409/17683194/25496b2c-630e-11e6-8e5c-c4ceec29ab79.png">
